import type { Id } from "../../../../convex/_generated/dataModel";
import type { ExerciseCandidate } from "../types";

export const FIXTURE_EXERCISES: ExerciseCandidate[] = [
  {
    _id: "ex_warmup" as Id<"exercises">,
    title: "Chromatic Warm-up",
    slug: "chromatic-warmup",
    coreSkillId: "synchronisation",
    subSkillIds: [],
    exerciseType: "warmup",
    difficultyLevel: 2,
    primaryProgressMetric: "clean_reps",
    supportsBpm: true,
    defaultTargetBpm: 80,
    estimatedMinutes: 5,
    isMvp: true,
    status: "active",
  },
  {
    _id: "ex_primary" as Id<"exercises">,
    title: "Alternate Picking 16ths",
    slug: "alternate-picking-16ths",
    coreSkillId: "picking",
    subSkillIds: ["alternate_picking"],
    exerciseType: "primary",
    difficultyLevel: 4,
    primaryProgressMetric: "clean_bpm",
    supportsBpm: true,
    defaultTargetBpm: 100,
    estimatedMinutes: 10,
    isMvp: true,
    status: "active",
  },
  {
    _id: "ex_secondary" as Id<"exercises">,
    title: "String Crossing Ladder",
    slug: "string-crossing-ladder",
    coreSkillId: "picking",
    subSkillIds: ["string_crossing"],
    exerciseType: "secondary",
    difficultyLevel: 4,
    primaryProgressMetric: "clean_bpm",
    supportsBpm: true,
    defaultTargetBpm: 90,
    estimatedMinutes: 8,
    isMvp: true,
    status: "active",
  },
  {
    _id: "ex_accessory" as Id<"exercises">,
    title: "Palm Mute Control",
    slug: "palm-mute-control",
    coreSkillId: "rhythm_timing",
    subSkillIds: ["palm_muting"],
    exerciseType: "accessory",
    difficultyLevel: 3,
    primaryProgressMetric: "noise_control",
    supportsBpm: true,
    defaultTargetBpm: 85,
    estimatedMinutes: 6,
    isMvp: true,
    status: "active",
  },
  {
    _id: "ex_isolation" as Id<"exercises">,
    title: "Fretting Accuracy 1-2-3-4",
    slug: "fretting-accuracy-1234",
    coreSkillId: "fretting_control",
    subSkillIds: ["fretting_accuracy"],
    exerciseType: "isolation",
    difficultyLevel: 3,
    primaryProgressMetric: "accuracy_score",
    supportsBpm: false,
    estimatedMinutes: 7,
    isMvp: true,
    status: "active",
  },
  {
    _id: "ex_test" as Id<"exercises">,
    title: "Picking Benchmark",
    slug: "picking-benchmark",
    coreSkillId: "picking",
    subSkillIds: ["alternate_picking"],
    exerciseType: "test",
    difficultyLevel: 5,
    primaryProgressMetric: "clean_bpm",
    supportsBpm: true,
    defaultTargetBpm: 110,
    estimatedMinutes: 8,
    isMvp: true,
    status: "active",
  },
];

export const FIXTURE_PROFILE = {
  primaryGoals: ["improve_technique"],
  focusCoreSkillIds: ["picking", "synchronisation"] as const,
  focusSubSkillIds: ["alternate_picking"] as const,
  availableDays: ["Monday", "Wednesday", "Friday"],
  defaultSessionLengthMinutes: 30,
  preferredIntensity: "moderate",
};

export const FIXTURE_RATINGS = [
  {
    skillTarget: { kind: "core" as const, id: "picking" as const },
    rating: 40,
    status: "developing" as const,
  },
  {
    skillTarget: { kind: "core" as const, id: "synchronisation" as const },
    rating: 60,
    status: "stable" as const,
  },
  {
    skillTarget: { kind: "core" as const, id: "fretting_control" as const },
    rating: 30,
    status: "weak" as const,
  },
  {
    skillTarget: { kind: "core" as const, id: "rhythm_timing" as const },
    rating: 35,
    status: "weak" as const,
  },
];
